language: fortran

before_install: 
 - export ROOT_DIR=`pwd`
 - sudo apt-get update -qq
 - sudo apt-get install -y gfortran 
 - sudo apt-get install -y mpich2 libmpich2-dev libmpich2-3 
 - sudo apt-get install -y liblapack-dev
 - wget http://www.fftw.org/fftw-3.3.4.tar.gz
 - tar xf fftw-3.3.4.tar.gz
 - cd fftw-3.3.4
 - ./configure --enable-mpi --prefix=${ROOT_DIR}/fftw3/
 - make
 - make install
 - cd ..

 - git clone https://github.com/maxhutch/nek-tests.git
 - cd nek-tests/RTI-LST/

before_script: 
 - ../../makenek RTI_LST $ROOT_DIR

script: 
 - sh ../../nekmpi RTI_LST 2 > test.out
 - grep DIV RTI_LST-2.out > div.ref
 - grep DIV test.out > div.test
 - diff div.ref div.test

