language: fortran

before_install: 
 - export ROOT_DIR=`pwd`
 - sudo apt-get update -qq
 - sudo apt-get install -y gfortran 
 - sudo apt-get install -y mpich2 libmpich2-dev libmpich2-3 
 - sudo apt-get install -y liblapack-dev
 - sudo apt-get install -y fftw3-dev
 - git clone https://github.com/maxhutch/nek-tests.git
 - cd nek-tests/RTI-LST/

before_script: 
 - ../../makenek RTI_LST $ROOT_DIR

script: 
 - sh ../../nekmpi RTI_LST 2 > test.out
 - grep -i maximum test.out | tail -20 > max.test
 - cat maximums.reference | tail -20 > max.ref
 - diff max.ref max.test

