language: fortran

before_install: 
 - export ROOT_DIR=`pwd`
 - sudo apt-get update -qq
 - sudo apt-get install -y mpich2 libmpich2-dev libmpich2-3 
 - sudo apt-get install -y liblapack-dev
 - sudo apt-get install -y fftw3-dev
 - sudo apt-get install -y gfortran 
 - sudo apt-get install -y python3
 - sudo apt-get install -y python3-numpy
 - git clone https://github.com/maxhutch/nek-tests.git
 - git clone https://github.com/maxhutch/nek-tools.git
 - cd nek-tests/RTI-LST/

before_script: 
 - python3 ../../nek-tools/genrun/genrun.py -u LST_f90.tusr -d LST.json --makenek=../../makenek rti-lst_f90
# - ../../makenek RTI_LST $ROOT_DIR

script: 
 - sh ../../nekmpi rti-lst_f90 4 > rti-lst_f90.out
 - grep "Max" rti-lst_f90.out > f90.grp
 - grep "Max" rti-lst_f77.out > f77.grp
 - python3 ../ndiff.py f90.grp f77.grp

