language: fortran

before_install: 
 - sudo apt-get update -qq
 - sudo apt-get install -y gfortran 
 - sudo apt-get install -y mpich2 libmpich2-dev libmpich2-3 
 - sudo apt-get install -y liblapack3 libblas3

 - git clone git@github.com:maxhutch/nek-tests.git
 - cd nek-tests/RTI-LST/

script: 
 - ../../makenek
