language: fortran

before_install: 
 - export ROOT_DIR=`pwd`
 - sudo apt-get update -qq
 - sudo apt-get install -y mpich2 libmpich2-dev libmpich2-3 
 - sudo apt-get install -y liblapack-dev
 - sudo apt-get install -y fftw3-dev
 - sudo apt-get install -y gfortran 
 - sudo apt-get install -y python3
 - sudo apt-get install -y python3-numpy
 - git clone https://github.com/maxhutch/nek-tests.git
 - git clone https://github.com/maxhutch/nek-tools.git
 - cd nek-tests/RTI-LST/

before_script: 
 - python3 ../../nek-tools/genrun/genrun.py -u LST_f90.usr -d LST.json --makenek=../../makenek RTI_LST
# - ../../makenek RTI_LST $ROOT_DIR

script: 
 - sh ../../nekmpi RTI_LST 2 > test.out
 - grep -i maximum test.out | tail -20 > max.test
 - cat maximums.reference | tail -20 > max.ref
 - cat max.test
 - cat max.ref
# - diff max.ref max.test

