language: fortran

addons:
  apt:
    packages:
    - mpich2
    - libmpich2-dev
    - liblapack-dev
    - fftw3-dev
    - gfortran
    - python3
    - python3-numpy

env:
 - TEST_SUITE=RTI-LST/LST
 - TEST_SUITE=RTI-LST/LST_fft
 - TEST_SUITE=RTI-LST/LST_all
 - TEST_SUITE=RTI-LST/LST_sym
 - TEST_SUITE=RTI-LST/LST_sym_half
 - TEST_SUITE=Hill/Hill
 - TEST_SUITE=lid/lid

before_install: 
 - export ROOT_DIR=`pwd`
 - git clone https://github.com/maxhutch/nek-tests.git
 - git clone https://github.com/maxhutch/nek-tools.git
 - cd nek-tests/$(dirname "$TEST_SUITE")

before_script: 
 - python3 ../../nek-tools/genrun/genrun.py -u *_f90.tusr -d $(basename "$TEST_SUITE").json --makenek=../../makenek test_f90
# - ../../makenek RTI_LST $ROOT_DIR

script: 
 - sh ../../nekmpi test_f90 4 > test_f90.out
 - grep "Max" test_f90.out > f90.grp
 - grep "Max" $(basename "$TEST_SUITE")_ref.out > f77.grp
 - python3 ../ndiff.py f90.grp f77.grp

